// The single style entry point — imported once by src/app/layout.tsx and the Storybook preview.
// Loads the global cascade first, then every component stylesheet (mirroring src/components).
// Add a component? Create src/styles/components/<layer>/Name.scss and add one import line here.

import '@/styles/base.scss';

// basics
import '@/styles/components/basics/Accordion.scss';
import '@/styles/components/basics/AccordionItem.scss';
import '@/styles/components/basics/Alert.scss';
import '@/styles/components/basics/Avatar.scss';
import '@/styles/components/basics/Badge.scss';
import '@/styles/components/dashboard/basics/BadgeCard.scss';
import '@/styles/components/basics/Breadcrumb.scss';
import '@/styles/components/basics/Button.scss';
import '@/styles/components/basics/Collapsible.scss';
import '@/styles/components/basics/Column.scss';
import '@/styles/components/basics/Columns.scss';
import '@/styles/components/basics/Container.scss';
import '@/styles/components/basics/Content.scss';
import '@/styles/components/basics/Divider.scss';
import '@/styles/components/basics/HeadingGroup.scss';
import '@/styles/components/basics/Icon.scss';
import '@/styles/components/basics/Indicator.scss';
import '@/styles/components/basics/Interactive.scss';
import '@/styles/components/basics/Link.scss';
import '@/styles/components/basics/Media.scss';
import '@/styles/components/basics/Pill.scss';
import '@/styles/components/basics/Progress.scss';
import '@/styles/components/basics/Rating.scss';
import '@/styles/components/dashboard/basics/RouteReveal.scss';
import '@/styles/components/basics/Section.scss';
import '@/styles/components/basics/ShinyText.scss';
import '@/styles/components/basics/Shortcut.scss';
import '@/styles/components/basics/Skeleton.scss';
import '@/styles/components/basics/SkeletonText.scss';
import '@/styles/components/basics/Spinner.scss';
import '@/styles/components/basics/Title.scss';

// components
import '@/styles/components/components/ArticleCard.scss';
import '@/styles/components/dashboard/components/AuditDetailList.scss';
import '@/styles/components/dashboard/components/BadgeGallery.scss';
import '@/styles/components/components/Card.scss';
import '@/styles/components/dashboard/components/Chart.scss';
import '@/styles/components/dashboard/components/ChatTranscript.scss';
import '@/styles/components/components/CheckboxGroup.scss';
import '@/styles/components/components/Combobox.scss';
import '@/styles/components/components/CookieConsent.scss';
import '@/styles/components/components/CustomCursor.scss';
import '@/styles/components/dashboard/components/DataTable.scss';
import '@/styles/components/dashboard/components/DatePicker.scss';
import '@/styles/components/components/DescriptionList.scss';
import '@/styles/components/components/Drawer.scss';
import '@/styles/components/components/EmbedWidget.scss';
import '@/styles/components/components/EmptyState.scss';
import '@/styles/components/dashboard/components/EventAdminCard.scss';
import '@/styles/components/components/EventCard.scss';
import '@/styles/components/components/FileUpload.scss';
import '@/styles/components/components/FilterBar.scss';
import '@/styles/components/components/Form.scss';
import '@/styles/components/components/Gallery.scss';
import '@/styles/components/dashboard/components/HighlightCard.scss';
import '@/styles/components/components/ImageList.scss';
import '@/styles/components/components/InputGroup.scss';
import '@/styles/components/dashboard/components/ListboxCards.scss';
import '@/styles/components/components/MarqueeTicker.scss';
import '@/styles/components/components/Menu.scss';
import '@/styles/components/components/Modal.scss';
import '@/styles/components/components/Notification.scss';
import '@/styles/components/components/Entry.scss';
import '@/styles/components/components/Meter.scss';
import '@/styles/components/components/Metric.scss';
import '@/styles/components/components/Moment.scss';
import '@/styles/components/dashboard/components/NotificationBell.scss';
import '@/styles/components/components/NumberField.scss';
import '@/styles/components/components/Pagination.scss';
import '@/styles/components/components/Panel.scss';
import '@/styles/components/components/Person.scss';
import '@/styles/components/components/PermissionGroups.scss';
import '@/styles/components/components/Popover.scss';
import '@/styles/components/components/RadioGroup.scss';
import '@/styles/components/components/ScrollArea.scss';
import '@/styles/components/components/ScrollProgress.scss';
import '@/styles/components/components/ScrollytellingTimeline.scss';
import '@/styles/components/components/SearchPalette.scss';
import '@/styles/components/dashboard/components/RowActions.scss';
import '@/styles/components/dashboard/components/SegmentedControl.scss';
import '@/styles/components/components/Slider.scss';
import '@/styles/components/dashboard/components/SurveyResultsView.scss';
import '@/styles/components/components/Swiper.scss';
import '@/styles/components/components/Switch.scss';
import '@/styles/components/components/Table.scss';
import '@/styles/components/components/Tabs.scss';
import '@/styles/components/dashboard/components/TeamMemberCard.scss';
import '@/styles/components/components/Timeline.scss';
import '@/styles/components/components/Toggle.scss';
import '@/styles/components/components/ToggleGroup.scss';
import '@/styles/components/components/Tooltip.scss';
import '@/styles/components/components/VideoLightbox.scss';

// contentBlocks
import '@/styles/components/contentBlocks/BentoGrid.scss';
import '@/styles/components/contentBlocks/CTABanner.scss';
import '@/styles/components/contentBlocks/ErrorState.scss';
import '@/styles/components/contentBlocks/EventTeaser.scss';
import '@/styles/components/contentBlocks/FaqAccordion.scss';
import '@/styles/components/contentBlocks/FeatureCards.scss';
import '@/styles/components/contentBlocks/GrowingMediaOnScroll.scss';
import '@/styles/components/contentBlocks/Hero.scss';
import '@/styles/components/contentBlocks/HighlightCards.scss';
import '@/styles/components/contentBlocks/IntroGrid.scss';
import '@/styles/components/contentBlocks/ItemCardGrid.scss';
import '@/styles/components/contentBlocks/LinkCardGrid.scss';
import '@/styles/components/contentBlocks/LogoCloud.scss';
import '@/styles/components/contentBlocks/NewsletterForm.scss';
import '@/styles/components/contentBlocks/PageHeader.scss';
import '@/styles/components/contentBlocks/ProfileCards.scss';
import '@/styles/components/contentBlocks/PhotoMosaic.scss';
import '@/styles/components/contentBlocks/Prose.scss';
import '@/styles/components/contentBlocks/Reviews.scss';
import '@/styles/components/contentBlocks/Showreel.scss';
import '@/styles/components/contentBlocks/SectionHeader.scss';
import '@/styles/components/contentBlocks/SpotlightQuote.scss';
import '@/styles/components/contentBlocks/StatBand.scss';
import '@/styles/components/contentBlocks/Steps.scss';
import '@/styles/components/contentBlocks/StickyShowcase.scss';
import '@/styles/components/contentBlocks/SubscribeToNewsletter.scss';
import '@/styles/components/contentBlocks/TextMedia.scss';
import '@/styles/components/contentBlocks/TitleText.scss';

// forms
import '@/styles/components/forms/Checkbox.scss';
import '@/styles/components/forms/Field.scss';
import '@/styles/components/forms/FieldDescription.scss';
import '@/styles/components/forms/FieldError.scss';
import '@/styles/components/forms/FieldGroup.scss';
import '@/styles/components/forms/FieldLabel.scss';
import '@/styles/components/forms/FieldLegend.scss';
import '@/styles/components/forms/FieldSet.scss';
import '@/styles/components/dashboard/forms/NotificationComposerForm.scss';
import '@/styles/components/forms/Radio.scss';
import '@/styles/components/forms/Select.scss';
import '@/styles/components/dashboard/forms/SurveyQuestionEditor.scss';
import '@/styles/components/forms/TextArea.scss';
import '@/styles/components/forms/TextInput.scss';

// structures
import '@/styles/components/structures/AnnouncementBar.scss';
import '@/styles/components/dashboard/structures/BottomTabBar.scss';
import '@/styles/components/dashboard/structures/CommandPalette.scss';
import '@/styles/components/dashboard/structures/ConventionInvolvementCard.scss';
import '@/styles/components/structures/Footer.scss';
import '@/styles/components/dashboard/structures/MediaGrid.scss';
import '@/styles/components/structures/MegaMenu.scss';
import '@/styles/components/dashboard/structures/ShiftCalendar.scss';
import '@/styles/components/structures/Navigation.scss';

// dashboard features (relocated from route-local sheets)
import '@/styles/components/dashboard/shell/Dashboard.scss';
import '@/styles/components/dashboard/inventory/Inventory.scss';
import '@/styles/components/dashboard/moderation/Moderation.scss';
import '@/styles/components/dashboard/finance/Finance.scss';
import '@/styles/components/dashboard/finance/Expenses.scss';
import '@/styles/components/dashboard/team/Team.scss';
import '@/styles/components/dashboard/surveys/Surveys.scss';
