import type { Page } from '@/lib/content';

// De evenementenpagina: proof of life. Con-datums zijn geverifieerd op de officiële con-sites
// (juli 2026). DAC publiceert zelf geen datums voor meetups en online events — die draaien via
// Discord — dus terugkerende events staan bewust in de teaser zonder datum.
export const evenementenPage: Page = {
	meta: {
		title: 'Evenementen',
		description: 'Watch parties, game nights, meetups en cons: bij DAC is het hele jaar door iets te doen — online en in het echt.',
	},
	blocks: [
		{
			type: 'ctaBanner',
			id: 'header',
			colorset: 'dark',
			tagline: 'Events',
			headline: 'Kom samen — online en IRL',
			subline: 'Het hele jaar door watch parties, game nights, meetups en cons.',
			media: { type: 'image', src: '/media/hmia-2024.png', alt: 'DAC-groepsfoto op Heroes Made in Asia' },
		},
		{
			type: 'eventCardGrid',
			id: 'cons',
			colorset: 'light',
			heading: {
				tagline: 'De grote cons',
				value: 'Hier vind je ons komend jaar',
				intro: 'Datums komen rechtstreeks van de officiële con-sites. Meegaan? In Discord spreken we af waar en hoe laat.',
			},
			columns: 2,
			sortLabel: 'Sorteer op',
			emptyMessage: 'Geen events gevonden.',
			sortOptions: [
				{ label: 'Eerstvolgende eerst', value: 'oldest' },
				{ label: 'Verste vooruit eerst', value: 'recent' },
			],
			events: [
				{
					id: 'con-abunai-2026',
					title: 'Abunai! 2026',
					summary: 'Drie dagen anime in Veldhoven. Grote kans dat je hier een flinke groep DAC\'ers tegenkomt — meetups worden in Discord geregeld.',
					startDate: '2026-08-07',
					endDate: '2026-08-09',
					location: 'NH Koningshof, Veldhoven',
					status: 'Con',
					statusVariant: 'primary',
					href: 'https://abunaicon.nl',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 'con-dcc-winter-2026',
					title: 'Heroes Dutch Comic Con — Winter 2026',
					summary: 'Onze drukste con van het jaar. Kom langs bij de zwart-gouden DAC-stand voor de anime-quiz, een potje galgje en de groepsfoto.',
					startDate: '2026-11-21',
					endDate: '2026-11-22',
					location: 'Jaarbeurs, Utrecht',
					status: 'Met DAC-stand',
					statusVariant: 'success',
					href: 'https://dutchcomiccon.com',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 'con-hmia-2027',
					title: 'Heroes Made in Asia 2027',
					summary: 'De grootste Azië-beurs van de Benelux, vanaf deze editie in Utrecht. DAC staat er traditiegetrouw met een eigen stand.',
					startDate: '2027-03-20',
					endDate: '2027-03-21',
					location: 'Jaarbeurs, Utrecht',
					status: 'Met DAC-stand',
					statusVariant: 'success',
					href: 'https://www.made-in-asia.nl',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 'con-animecon-2027',
					title: 'AnimeCon 2027',
					summary: 'Drie dagen anime, cosplay en optredens in Rijswijk — met elk jaar een gezellige DAC-delegatie.',
					startDate: '2027-04-16',
					endDate: '2027-04-18',
					location: 'De Broodfabriek, Rijswijk',
					status: 'Con',
					statusVariant: 'primary',
					href: 'https://animecon.nl',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
			],
		},
		{
			type: 'eventTeaser',
			id: 'terugkerend',
			colorset: 'dark',
			heading: {
				tagline: 'Elke week iets',
				value: 'Terugkerende events',
				intro: 'Hier heb je geen agenda voor nodig: de datums en aanmeldingen gaan altijd via Discord.',
			},
			events: [
				{
					id: 're-watchparty',
					title: 'Watch party',
					summary: 'Samen een anime of film kijken, met live reacties in de chat.',
					location: 'Online — Discord',
					status: 'Wekelijks',
					statusVariant: 'success',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 're-gamenight',
					title: 'Game night',
					summary: 'Party games, toernooitjes of bouwen op de Minecraft-server — iedereen kan aanhaken.',
					location: 'Online — Discord',
					status: 'Wekelijks',
					statusVariant: 'success',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 're-weerwolven',
					title: 'Weerwolven van Wakkerdam',
					summary: 'Ons eigen async spel: één spel-dag per echte dag, dus je doet mee wanneer het jou uitkomt.',
					location: 'Online — Discord',
					status: 'Rondes door het jaar',
					statusVariant: 'info',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 're-spelletjes',
					title: 'Spelletjesmiddag',
					summary: 'Bordspellen, kaartspellen en veel gelach — een meetup in het echt.',
					location: 'Den Haag',
					status: 'Terugkerend',
					statusVariant: 'info',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 're-uitjes',
					title: 'Dagjes uit',
					summary: 'Van een middag Rotterdam tot een dag pretpark — samen eropuit met de crew.',
					location: 'Heel Nederland',
					status: 'Paar keer per jaar',
					statusVariant: 'info',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
			],
		},
		{
			type: 'textMedia',
			id: 'stand',
			colorset: 'light',
			title: 'Kom langs bij onze stand',
			text: 'Zwarte banner, gouden logo, art prints en bordspellen op tafel — zo herken je de DAC-stand op de con. Doe mee met de anime-quiz, waag een potje galgje, of maak een groepsfoto met de crew. Even hoi zeggen is genoeg om je meteen thuis te voelen.',
			media: { type: 'image', src: '/media/dac-stand.jpg', alt: 'De DAC-stand op een conventie' },
			reverse: true,
		},
		{
			type: 'photoMosaic',
			id: 'terugblik',
			colorset: 'light',
			variant: 'scrapbook',
			heading: {
				tagline: 'Zo was het',
				value: 'Een kijkje bij eerdere edities',
				intro: 'Foto\'s van onze stands en groepsmomenten op de afgelopen cons.',
			},
			items: [
				{ id: 'tb-dcc-2024', media: { type: 'image', src: '/media/dcc-2024.png', alt: 'DAC-groepsfoto op Dutch Comic Con 2024' }, caption: 'Dutch Comic Con 2024 — de tiende editie' },
				{ id: 'tb-hmia-2024', media: { type: 'image', src: '/media/hmia-2024.png', alt: 'DAC-groepsfoto op Heroes Made in Asia in Gorinchem' }, caption: 'Heroes Made in Asia 2024' },
				{ id: 'tb-dcc-2023', media: { type: 'image', src: '/media/dcc-2023-highlights.png', alt: 'Hoogtepunten van DAC op Dutch Comic Con 2023' }, caption: 'Dutch Comic Con 2023 — waar het begon' },
				{ id: 'tb-stand', media: { type: 'image', src: '/media/dac-stand.jpg', alt: 'De DAC-stand op een conventie' }, caption: 'De stand: zwarte banner, gouden logo' },
				{ id: 'tb-spellen', media: { type: 'image', src: '/media/spelletjesmiddag.jpg', alt: 'Bordspellen op een DAC-spelletjesmiddag' }, caption: 'Spelletjesmiddag in Den Haag' },
				{ id: 'tb-meetup', media: { type: 'image', src: '/media/dac-meetup.png', alt: 'Grote groepsfoto op een DAC-meetup' }, caption: 'Meetup met de hele crew' },
			],
		},
		{
			type: 'ctaBanner',
			id: 'word-lid',
			colorset: 'dark',
			tagline: 'Zin in?',
			headline: 'Mis het volgende event niet',
			subline: 'Alle events worden aangekondigd in Discord. Join gratis en je hoort er meteen bij.',
			primaryCta: { label: 'Word lid', variant: 'primary', url: 'https://discord.gg/dutchanimecommunity', target: '_blank' },
			secondaryCta: { label: 'Zo werkt het', variant: 'secondary', url: '/word-lid' },
			tone: 'primary',
			align: 'center',
			media: { type: 'image', src: '/media/amelia-smile.webp', alt: 'Amelia, de DAC-mascotte, kijkt vrolijk over de rand', mode: 'fit', ratio: '1 / 1' },
		},
	],
};
