import type { Page } from '@/lib/content';

// De homepage: de pitch + het bewijs, en overal dezelfde ene actie — Word lid. Elke sectie
// beantwoordt "what's in it for me?" voor een anime-fan van 16-36: vrienden maken, samen dingen
// doen, en een plek om je art en cosplay te laten zien. Con-datums zijn geverifieerd op de
// officiële con-sites (juli 2026); DAC publiceert zelf geen meetup-datums, dus terugkerende events
// staan bewust zonder datum. De reviews zijn echte Disboard-reviews.
export const homePage: Page = {
	meta: {
		title: 'De gezelligste anime-community van Nederland',
		description: 'Dutch Anime Community is de grootste Nederlandstalige anime-community: 4.500+ leden, watch parties, game nights, meetups en een eigen stand op de cons. Word gratis lid via Discord.',
	},
	blocks: [
		{
			type: 'hero',
			id: 'intro',
			colorset: 'dark',
			variant: 'cover',
			tagline: 'De gezelligste anime-community van Nederland',
			title: 'Vind je crew. Kijk samen. Voel je thuis.',
			text: 'De grootste Nederlandstalige anime- en mangacommunity — voor en door fans. Of je nu leeft voor cosplay, non-stop gamet of net je eerste anime hebt ontdekt: bij ons is er altijd iemand online en altijd een plek voor jou.',
			media: { type: 'image', src: '/media/dac-meetup.png', alt: 'DAC-leden samen op een meetup' },
			actions: [
				{ label: 'Word lid', variant: 'primary', url: 'https://discord.gg/dutchanimecommunity', target: '_blank' },
				{ label: 'Hoe werkt het?', variant: 'ghost', url: '/word-lid' },
			],
			stats: [
				{ count: '4.500+', label: 'leden' },
				{ count: '1.000+', label: 'tegelijk online' },
				{ count: '4', label: 'cons per jaar' },
				{ count: '100%', label: 'gratis' },
			],
			socials: [
				{ label: 'Discord', url: 'https://discord.gg/dutchanimecommunity', target: '_blank' },
				{ label: 'Instagram', url: 'https://www.instagram.com/dutchanimecommunity/', target: '_blank' },
				{ label: 'TikTok', url: 'https://www.tiktok.com/@dutchanimecommunity', target: '_blank' },
			],
		},
		{
			type: 'highlightCards',
			id: 'wiifm',
			colorset: 'light',
			heading: {
				tagline: 'Wat het jou oplevert',
				value: 'Waarom je bij DAC wilt zijn',
				intro: 'Geen account-gedoe, geen drempels. Gewoon een warme plek vol mensen die net zo hard van anime houden als jij.',
			},
			columns: 3,
			items: [
				{
					id: 'wiifm-vrienden',
					media: { type: 'image', src: '/media/dcc-2024.png', alt: 'DAC-groepsfoto bij de stand op Dutch Comic Con' },
					tagline: 'Vrienden',
					title: 'Maak snel nieuwe vrienden',
					text: 'Zeg hoi en je zit zo in een gesprek. Veel leden maken hier hun eerste online vrienden — en zien elkaar later gewoon in het echt op een meetup.',
				},
				{
					id: 'wiifm-samen',
					media: { type: 'image', src: '/media/spelletjesmiddag.jpg', alt: 'Bordspellen op een DAC-spelletjesmiddag' },
					tagline: 'Samen',
					title: 'Altijd iets te doen',
					text: 'Watch parties, game nights, een eigen Minecraft-server en spelletjesmiddagen. Er is altijd wel iemand wakker om mee te kijken of te gamen.',
				},
				{
					id: 'wiifm-art',
					media: { type: 'image', src: '/media/dcc-2023-highlights.png', alt: 'Cosplayers en DAC-activiteiten op een con' },
					tagline: 'Laat je zien',
					title: 'Deel je art & cosplay',
					text: 'We hebben een grote creatieve hoek. Post je tekeningen, foto\'s of verhalen, krijg reacties van fans — en sta straks misschien met ons op de con.',
				},
			],
		},
		{
			type: 'stickyShowcase',
			id: 'journey',
			colorset: 'light',
			heading: {
				tagline: 'Zo groei je erin',
				value: 'Van eerste hoi tot con-crew',
				intro: 'Niemand hoeft meteen vooraan te staan. Dit is hoe het voor de meeste leden gaat.',
			},
			steps: [
				{
					id: 'j-hoi',
					title: 'Zeg hoi op Discord',
					body: 'Eén klik en je bent binnen — gratis, zonder gedoe. Stel jezelf voor in het welkomstkanaal en grote kans dat je binnen een uur je eerste gesprek te pakken hebt.',
					media: { type: 'image', src: '/media/amelia-hug.webp', alt: 'Amelia, de DAC-mascotte, verwelkomt je' },
				},
				{
					id: 'j-meedoen',
					title: 'Doe mee met watch parties & games',
					body: 'Kijk samen een aflevering, schuif aan bij een game night of bouw mee op de Minecraft-server. Meedoen mag, meekijken ook.',
					media: { type: 'image', src: '/media/spelletjesmiddag.jpg', alt: 'Bordspellen tijdens een DAC-spelletjesmiddag' },
				},
				{
					id: 'j-meetup',
					title: 'Ga mee naar een meetup',
					body: 'Van spelletjesmiddagen tot dagjes uit: de mensen achter de usernames blijken in het echt net zo gezellig.',
					media: { type: 'image', src: '/media/dac-meetup.png', alt: 'DAC-leden samen op een meetup' },
				},
				{
					id: 'j-con',
					title: 'Sta samen op de con',
					body: 'Het hoogtepunt van het jaar: met de crew naar Dutch Comic Con of Heroes Made in Asia — inclusief anime-quiz en de traditionele groepsfoto.',
					media: { type: 'image', src: '/media/dac-stand.jpg', alt: 'De DAC-stand op een conventie' },
				},
			],
		},
		{
			type: 'bentoGrid',
			id: 'binnen-de-server',
			colorset: 'dark',
			heading: {
				tagline: 'Binnen de server',
				value: 'Zoveel meer dan chatten',
				intro: 'Van samen kijken tot samen bouwen — dit gebeurt er elke dag.',
			},
			columns: 4,
			items: [
				{ id: 'b-fans', span: 'feature', media: { type: 'image', src: '/media/amelia.png', alt: 'Amelia, de mascotte van DAC' }, tagline: 'Voor en door fans', title: 'Dit is jouw plek', body: 'Anime, manga, games, art — en gewoon je dag delen. Amelia, onze mascotte, heet je alvast welkom.' },
				{ id: 'b-watch', span: 'standard', surface: 'accent', tagline: 'Samen kijken', title: 'Watch parties', body: 'Samen kijken, samen reageren.' },
				{ id: 'b-game', span: 'standard', tagline: 'Gamen', title: 'Game nights & Minecraft', body: 'Van toernooitjes tot chillen op onze eigen server.' },
				{ id: 'b-art', span: 'standard', surface: 'muted', tagline: 'Creatief', title: 'Creatieve hoek', body: 'Jouw art, foto\'s en verhalen verdienen publiek.' },
				{ id: 'b-weerwolven', span: 'wide', surface: 'inverse', tagline: 'Ons eigen spel', title: 'Weerwolven van Wakkerdam', body: 'Eén spel-dag duurt een echte dag, dus je doet mee wanneer het jou uitkomt. Vorm allianties, stem elke dag, overleef de nacht.' },
				{ id: 'b-cosplay', span: 'standard', tagline: 'Cosplay', title: 'Cosplay & meetups', body: 'Online hype, offline afspreken.' },
				{ id: 'b-media', span: 'standard', surface: 'accent', tagline: 'Meer dan anime', title: 'Muziek, films & series', body: 'Ook buiten anime genoeg te bespreken.' },
				{ id: 'b-cultuur', span: 'standard', surface: 'muted', tagline: 'Cultuur', title: 'Japan & Korea', body: 'Van taal en tradities tot street food.' },
			],
		},
		{
			type: 'showreel',
			id: 'in-beeld',
			colorset: 'light',
			heading: {
				tagline: 'Community in beeld',
				value: 'Zo ziet gezellig eruit',
				intro: 'Echte foto\'s van echte leden — op cons, meetups en spelletjesmiddagen.',
			},
			ratio: '848 / 488',
			slides: [
				{ image: '/media/dac-meetup.png', alt: 'Grote groepsfoto op een DAC-meetup', title: 'Meetup met de crew', description: 'De mensen achter de usernames, gewoon in het echt.' },
				{ image: '/media/dcc-2024.png', alt: 'Groepsfoto op Dutch Comic Con 2024', title: 'Dutch Comic Con 2024', description: 'De tiende editie, met de drukste stand tot nu toe.' },
				{ image: '/media/spelletjesmiddag.jpg', alt: 'Bordspellen op een spelletjesmiddag', title: 'Spelletjesmiddag', description: 'Bordspellen, kaartspellen en veel gelach in Den Haag.' },
				{ image: '/media/hmia-2024.png', alt: 'Groepsfoto op Heroes Made in Asia', title: 'Heroes Made in Asia', description: 'Twee dagen cosplay en groepsfoto\'s bij onze stand.' },
				{ image: '/media/dcc-2023-highlights.png', alt: 'Cosplay en activiteiten op Dutch Comic Con 2023', title: 'Dutch Comic Con 2023', description: 'Waar het stand-avontuur groot werd.' },
			],
		},
		{
			type: 'spotlightQuote',
			id: 'spotlight',
			colorset: 'dark',
			quote: 'Ik heb hier een paar van mijn beste vrienden ontmoet. Het heeft me geholpen om mezelf te zijn — en door deze server durf ik nu naar cons te gaan.',
			author: 'Pejowo',
			role: 'lid, review op Disboard',
			mascot: { type: 'image', src: '/media/amelia-smile.webp', alt: '', mode: 'fit', ratio: '1 / 1' },
		},
		{
			type: 'eventTeaser',
			id: 'events',
			colorset: 'light',
			heading: {
				tagline: 'Altijd wat te doen',
				value: 'Waar je ons vindt',
				intro: 'Online events door de week, en het hele jaar door meetups en cons.',
			},
			events: [
				{
					id: 'ev-watchparty',
					title: 'Watch party',
					summary: 'Samen een anime kijken en live meepraten — gewoon vanaf je bank.',
					location: 'Online — Discord',
					status: 'Wekelijks',
					statusVariant: 'success',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 'ev-abunai',
					title: 'Abunai! 2026',
					summary: 'Drie dagen anime in Veldhoven — grote kans dat je hier een flinke groep DAC\'ers tegenkomt.',
					startDate: '2026-08-07',
					endDate: '2026-08-09',
					location: 'NH Koningshof, Veldhoven',
					status: 'Con',
					statusVariant: 'primary',
					href: 'https://abunaicon.nl',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
				{
					id: 'ev-dcc-winter',
					title: 'Heroes Dutch Comic Con — Winter',
					summary: 'Onze drukste con: kom langs bij de zwart-gouden DAC-stand voor de anime-quiz en een groepsfoto.',
					startDate: '2026-11-21',
					endDate: '2026-11-22',
					location: 'Jaarbeurs, Utrecht',
					status: 'Con',
					statusVariant: 'primary',
					href: 'https://dutchcomiccon.com',
					translations: { timeLabel: 'Tijd', locationLabel: 'Locatie' },
				},
			],
			viewAllUrl: '/evenementen',
			viewAllLabel: 'Alle evenementen',
		},
		{
			type: 'logoCloud',
			id: 'cons',
			colorset: 'light',
			heading: { value: 'Je komt ons hier tegen' },
			description: 'Plus: ook op Heroes Made in Asia en AnimeCon kom je de crew tegen.',
			variant: 'grid',
			items: [
				{ id: 'lg-dcc', name: 'Heroes Dutch Comic Con', logo: '/media/logos/dutch-comic-con.svg', href: 'https://dutchcomiccon.com' },
				{ id: 'lg-abunai', name: 'Abunai!', logo: '/media/logos/abunai.svg', href: 'https://abunaicon.nl' },
			],
		},
		{
			type: 'ctaBanner',
			id: 'word-lid',
			colorset: 'dark',
			tagline: 'Klaar?',
			headline: 'Kom erbij — je crew wacht al op je',
			subline: '4.500+ leden, en er is altijd wel iemand wakker. Tot zo!',
			primaryCta: { label: 'Word lid', variant: 'primary', url: 'https://discord.gg/dutchanimecommunity', target: '_blank' },
			secondaryCta: { label: 'Wat is Discord?', variant: 'secondary', url: 'https://discord.com/safety/360044149331-What-is-Discord', target: '_blank' },
			tone: 'primary',
			align: 'center',
		},
	],
};
